name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: name of the event that triggered the workflow
        run: |
          echo "event: ${{ github.event_name }}"
      - name: name of the branch that the repository
        run: |
          echo "${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
        
            
  
    
